x/stake/cross_stake/cross_stake.go
x/stake/keeper/distribute_sidechain.go
x/stake/types/cross_stake.go
x/stake/types/cross_stake_test.go

There may be some vulnerability in previous native staking design. 
N/A
For example, if a user sends the `delegate` transaction with invalid validator, execute the `undelegate` transaction immediately before receiving the AckPackage of the last delegate transaction, the token from the last delegate transaction will be locked.
For now, every request from BSC to BC will have an ack package to inform the status of the request. State changes will be done only after the ack package with success status is received.

fix: update cross chain logic of native stake

---

x/stake/cross_stake/cross_stake.go
x/stake/keeper/distribute_sidechain.go
x/stake/types/cross_stake.go
x/stake/types/cross_stake_test.go

There may be some vulnerability in previous native staking design. 
N/A
For example, if a user sends the `delegate` transaction with invalid validator, execute the `undelegate` transaction immediately before receiving the AckPackage of the last delegate transaction, the token from the last delegate transaction will be locked.
For now, every request from BSC to BC will have an ack package to inform the status of the request. State changes will be done only after the ack package with success status is received.

fix: update cross chain logic of native stake (#295)

---

cmd/gaia/cmd/gaiacli/main.go
x/stake/client/cli/cmd.go
x/stake/client/cli/query.go
x/stake/client/cli/query_sidechain.go
x/stake/keeper/distribute_sidechain.go
x/stake/querier/queryable.go
x/stake/stake.go

Add a tag for recon service and query api for user to get their cross stake reward by their bsc address
N/A
N/A
- Add `QueryCrossStakeRewardByBscAddress` method
- Adjust total reward distrituion tag

feat: add tag and query API for cross stake reward

---

types/upgrade.go
x/gov/handler_sidechain.go
x/gov/proposals_sidechain.go

"Text" accepted as a valid BNB Smart Chain proposalType in proposals_sidechain.go
BEP154 upgrade validation to be handled in handler_sidechain.go
Tested the implementation before and after the BEP173 upgrade. Proposal type "Text" is accepted after the BEP173 upgrade.  
Commands:
Submit Text Proposal
./tbnbcli gov submit-proposal --type text …[flags]
Query Proposal
./tbnbcli gov query-proposal --proposal-id {id} ...[flags]
Voting 
./tbnbcli gov vote --option yes --proposal-id {id} ...[flags]

bep173: enable text proposal on BNB Smart Chain

---

x/stake/client/cli/cmd.go
x/stake/client/cli/query_sidechain.go
x/stake/querier/queryable.go
x/stake/stake.go
x/stake/types/cross_stake.go

Rename the query method of cross stake reward to `QueryCrossStakeInfoByBscAddress` and add delegation address and reward address to the response.
N/A
N/A
- Rename `QueryCrossStakeRewardByBscAddress` method to `QueryCrossStakeInfoByBscAddress`
- Add delegation address and reward address to the response

query: enrich cross stake info query

---

CHANGELOG.md
x/stake/client/cli/cmd.go
x/stake/client/cli/query_sidechain.go
x/stake/querier/queryable.go
x/stake/stake.go
x/stake/types/cross_stake.go

This PR prepares for the release v0.25.6. 
This should be a hard fork release.
Changelogs:
* [sdk] [\#312](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/312) hardfork: add bsc chainID to encodeSigHeader when submitting evidence for slashing
* [sdk] [\#294](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/294) BEP153: Native Staking Implementation
It is a hardfork release, everyone is encouraged to upgrade to latest version.

docs: add change logs for release v0.25.6

---

x/slashing/client/cli/cmd.go

Add `Unjail` cli support.
Example:
```
$ ./build/tbnbcli slashing unjail -h
unjail validator previously jailed for downtime
Usage:
bnbcli slashing unjail [flags]
Flags:
--account-number int   AccountNumber number to sign the tx
--async                broadcast transactions asynchronously
--chain-id string      Chain ID of tendermint node
--dry                  Generate and return the tx bytes (do not broadcast)
--dry-run              ignore the perform a simulation of a transaction, but don't broadcast it
--from string          Name or address of private key with which to sign
--generate-only        build an unsigned transaction and write it to STDOUT
-h, --help                 help for unjail
--indent               Add indent to JSON response
--json                 return output in json …
```

feat: support unjail cli

---

x/params/subspace/subspace.go

Previous error example:
```bash
$ ./build/tbnbcli params side-params --trust-node --side-chain-id bsc
ERROR: {"codespace":1,"code":1,"abci_code":65537,"message":"internal error"}
```
Output example after the fix:
```bash
$ ./build/tbnbcli params side-params --trust-node --side-chain-id bsc
[
{
"type": "params/IbcParamSet",
"value": {
"relayer_fee": "1000000"
}
},
{
"type": "params/StakeParamSet",
"value": {
"unbonding_time": "604800000000000",
"max_validators": 21,
"bond_denom": "BNB",
"min_self_delegation": "2000000000000",
"min_delegation_change": "100000000",
"reward_distribution_batch_size": "1000",
"max_stake_snapshots": 0,
"base_proposer_reward_ratio": "0",
"bonus_proposer_reward_ratio": "0",
"fee_from_bsc_to_bc_ratio": "0"
}
},
{
"type": "params/SlashParamSet",
"value": { …
```

fix bnbcli params side-params error

---

types/context.go
x/paramHub/hub.go
x/stake/genesis.go
x/stake/keeper/params.go

This pr will fix the [syncing issue of testnet](https://github.com/bnb-chain/node/issues/916). 
The root cause is the genesis params are changed after the testnet setup and the genesis params are not read from the genesis file but from the code. 
This pr will fix the breaking change of the genesis params so users can syncing from genesis state for tesnet.

fix: fix the breaking change of genesis state for testnet

---

CHANGELOG.md

This PR prepares for the release v0.25.7. 
This should be a hard fork release.
Changelogs:
* [sdk] [\#320](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/320) fix: the breaking change of genesis state for testnet
* [sdk] [\#319](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/319) dep: update deps that were reported in OSV issues
* [sdk] [\#318](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/318) feat: limit sidechain consensus addr update interval
* [sdk] [\#317](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/317) fix: bnbcli params side-params error
* [sdk] [\#316](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/316) feat: support unjail cli
It is a hordfork release(LimitConsAddrUpdateInterval), it includes several bug fixes, and security updates.

docs: add change logs for release v0.25.7

---

types/coin.go
types/coin_test.go

The `Plus/Minus` functions do not handle amount calculation correctly for some special cases. This pr will add `safePlus` `safeMinus` helper functions to handle the issue.
Fix amount calculation issues.
NA

fix: update Coin to fix amount calculation issues

---

CHANGELOG.md

This PR prepares for the release v0.25.8. 
This should be a security patch release.
Changelogs:
* [sdk] [\#323](https://github.com/bnb-chain/bnc-cosmos-sdk/pull/323) fix: update Coin to fix amount calculation issues
NA
It is a patch release, which includes several bug fixes.

docs: add change logs for release v0.25.8

---

go.mod
go.sum
store/iavlstore.go
store/multistoreproof.go
store/multistoreproof_test.go
store/proof.go
store/proofs/convert.go
store/proofs/convert_test.go
store/proofs/create.go
store/proofs/create_test.go
store/proofs/helpers.go
store/proofs/random.go
store/rootmultistore.go
store/rootmultistore_test.go
types/upgrade.go

This pr will add ics23 proof to the multistore query. 
The new query path `ics23-key` will return ics23 proof if proof is requested.
Example ics23 proof query:
```go 
query := abci.RequestQuery{
Path: "/ibc/ics23-key", 
Data: []byte("key"), 
Height: ver,
Prove: true,
}
```
Also, we change the hash calculation of the root multistore (aka app hash), the reason is we can apply the ics23 proof directly by doing this.
https://github.com/cosmos/cosmos-sdk/blob/c303d7f3417f67818bc1d2dce6b53732b0db81e4/store/types/commit_info.go#L23

[R4R] add ics23 proof support

---

x/stake/handler_sidechain.go
x/stake/stake.go
x/stake/types/errors.go
x/stake/types/msg_sidechain.go

Currently the BEP159 upgrade check is placed in the `validateBasic` function which is stateless and dont have the context about block height,  it will cause the wrong check on cmd and SDK.
We move the check to the handler instead of `validateBasic`.
It wont impact the on-chain logic and will not cause hardfork.
No

fix: place the upgrade check in right place

---

CHANGELOG.md
x/stake/keeper/params.go

This PR aims to release v0.26.1, which fixes a bug introduced by https://github.com/bnb-chain/bnc-cosmos-sdk/pull/320.
Fix the syncing issue.
* [sdk] [\#331] (https://github.com/bnb-chain/bnc-cosmos-sdk/pull/331) fix: fix the bug introduced by fixing the testnet syncing issue

release: prepare for the release v0.26.1

---

client/context/query.go

This pr fixes an issue of cli client after the upgrade of BEP171.

fix: fix cli query merkle proof invalid issue

---

CHANGELOG.md
client/context/query.go

This pr prepares for the release of v0.26.2, which is a bug-fix release.
(https://github.com/bnb-chain/bnc-cosmos-sdk/pull/336) fix: fix merkle proof invalid issue of cli query
```
❯ ./tbnbcli token info --symbol BUSD-BAF --chain-id=Binance-Chain-Ganges --node=data-seed-pre-0-s3.binance.org:80
{
"type": "bnbchain/Token",
"value": {
"name": "BUSD token",
"symbol": "BUSD-BAF",
"original_symbol": "BUSD",
"total_supply": "16000000.00000000",
"owner": "tbnb15yqj8s26vvf4l62954pr9wh8ltypwuzkmqwre4",
"mintable": false,
"contract_address": "0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee",
"contract_decimals": 18
}
}
```

release: prepares for the release of v0.26.2

---

types/stake.go
x/slashing/errors.go
x/slashing/execute_test.go
x/slashing/keeper.go
x/slashing/slash_record.go
x/slashing/types.go
x/stake/keeper/sdk_types.go
x/stake/types/validator.go

Description
introduce a new type of slashing for malicious vote.
it's trigged by crossschain package from systemscontracts in bsc and reuse params of double sign slashing, with following features:
a. one validator can't be slashed when it has been slashed for malicious vote previous and still in jail
b. validator can't escape from slashing by editing vote address after malicious vote
Rationale
Example
tested in new qa
Changes
NA

new slash mechanism

---

store/rootmultistore.go
types/upgrade.go

This pr will fix the issue that we can not get the right commit id when there is a fork to calculate the hash of the merkle tree.
It will use the height of the commit itself to check the upgrade status instead of the height set in begin block when calculating the hash of the merkle trees.
Fix issue calculate store hash.
N/A
Notable changes:
* use height in store for checking upgrade status

fix: use height in store for checking upgrade status

---

CHANGELOG.md

This prs prepares for release v0.26.4, which is a bug fix release.
(https://github.com/bnb-chain/bnc-cosmos-sdk/pull/345) fix: fix validator unmarshal failed issue

docs: update change log for release v0.26.4

---

x/slashing/client/cli/query_sidechain.go
x/slashing/slash_record.go

Description
support query history about malicious vote slash
Rationale
Example
tested in new qa
Changes
NA

fix: support querying history about malicious vote slash

---

CHANGELOG.md
x/slashing/client/cli/query_sidechain.go
x/slashing/slash_record.go
x/stake/types/validator.go

This pr drafts the release v0.26.5, which is a bug fix release.
* [cli] [\#348]  
* [cli] [\#350]

release: draft release for v0.26.5

---

CHANGELOG.md

This pr prepares for release v0.26.6, which mainly includes following changes.
For more information about bep255, please refer to https://github.com/bnb-chain/BEPs/blob/master/BEP255.md
* #349
* #353

docs: update change log for release v0.26.6

---

x/slashing/keeper.go

This pr will fix nil validator issue when publishing messages.

fix: fix nil validator when publishing message

---

x/ibc/keeper.go
x/stake/endblock.go

handleMsgSideChainUndelegate should not use the prefixCtx
```
"UnmarshalJSON cannot decode empty bytes"
goroutine 128 [running]:
runtime/debug.Stack()
\truntime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2()
\tgithub.com/tendermint/tendermint@v0.35.9/consensus/state.go:614 +0x4c
panic({0x16a9940, 0xc00ddd0630})
\truntime/panic.go:884 +0x213
github.com/cosmos/cosmos-sdk/x/params/subspace.Subspace.Get({_, {_, _}, {_, _}, {_, _, _}, {_}}, {{0x1d7eaa0, ...}, ...}, ...)
\tgithub.com/cosmos/cosmos-sdk@v0.25.0/x/params/subspace/subspace.go:80 +0x148
github.com/cosmos/cosmos-sdk/x/sidechain.Keeper.BscSideChainId({{0x1d73bf8, 0xc0008d3c40}, {0xc000a08150, {0x1d73bf8, 0xc0008d3bd0}, {0x1d73c20, 0xc0008d3c70}, {0xc0000440f0, 0x9, 0x17}, …
```

fix: panic issue when doing refundStake and closeCorssChainChannel

---

x/paramHub/genesis.go
x/paramHub/hub.go
x/stake/client/cli/cmd.go
x/stake/client/cli/flags.go
x/stake/client/cli/tx_sidechain.go
x/stake/cross_stake/cross_stake.go
x/stake/handler.go
x/stake/handler_sidechain.go
x/stake/keeper/delegation.go
x/stake/keeper/distribute.go
x/stake/keeper/ibc.go
x/stake/keeper/keeper.go
x/stake/stake.go
x/stake/stake_migration/alias.go
x/stake/stake_migration/pub.go
x/stake/stake_migration/serialize.go
x/stake/stake_migration/stake_migration.go
x/stake/types/stake_migration.go

This pr is to add `MsgSideChainStakeMigration` and `StakeMigrationApp`.
Notable changes:
* add `MsgSideChainStakeMigration` and `StakeMigrationApp`

feat: add `MsgSideChainStakeMigration` and `StakeMigrationApp`

---

x/paramHub/hub.go
x/paramHub/types/types.go
x/stake/types/codec.go

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/develop/CONTRIBUTING.md#pr-targeting))
______
For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

fix: add missing register for new msg

---

x/stake/handler_sidechain.go
x/stake/types/stake_migration.go

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/develop/CONTRIBUTING.md#pr-targeting))
______
For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

fix: add missing event

---

x/ibc/endblock.go

fix: close mirror, mirrorSync channel after FinalSunsetFork
mirror, mirrorSync channel was enabled by BEP84(https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP84.md) 
Those channels were bsc side channels, so they would not be in the bc store.

fix: close mirror, mirrorSync channel after FinalSunsetFork

---

x/stake/endblock.go
x/stake/handler.go
x/stake/keeper/delegation.go

fix: disable MsgEditSideChainValidator after FirstSunsetFork and refine codes

fix: disable MsgEditSideChainValidator after FirstSunsetFork and refine codes

---

CHANGELOG.md
x/stake/endblock.go

publish UnbondingDelegation events to `kafka` in EndBlock

fix: publish completed UnbondingDelegation events to kafka in EndBlock

---

crypto/ledger_secp256k1.go

New: v0.10.18
```
./build/tbnbcli.new staking bsc-delegate --amount 20000021:BNB --validator bva1pnww8kx30sz4xfcqvn8wjhrn796nf4dq77hcpa --side-chain-id chapel --chain-id Binance-Chain-Ganges --node https://data-seed-pre-0-s1.bnbchain.org:443 --trust-node --from ld0 --ledger
DEBUG!!! msgByte: {"account_number":"91733","chain_id":"Binance-Chain-Ganges","data":null,"memo":"","msgs":[{"type":"cosmos-sdk/MsgSideChainDelegate","value":{"delegation":{"amount":"20000021","denom":"BNB"},"delegator_addr":"tbnb1v4wm6hexfkxgv7gu2va6adn2qg7udz3l73g9cc","side_chain_id":"chapel","validator_addr":"bva1pnww8kx30sz4xfcqvn8wjhrn796nf4dq77hcpa"}}],"sequence":"16","source":"0"}
Please confirm if address displayed on ledger is identical to tbnb1v4wm6hexfkxgv7gu2va6adn2qg7udz3l73g9cc (yes/no)?yes
Please verify …
```

fix: ledger sig conversion
